
import 'dotenv/config';
import { db } from '../src/lib/db';
import { createTemporaryOrderAction, confirmTemporaryOrderAction, cancelTemporaryOrderAction } from '../src/app/actions/checkout-flow';

// Mock console.error to suppress expected Next.js errors during standalone execution
const originalConsoleError = console.error;
console.error = (...args) => {
    if (args[0]?.includes?.('Error creating order') || args[0]?.message?.includes?.('Invariant: static generation store')) {
        // Ignore Next.js specific errors in standalone script
        return;
    }
    originalConsoleError(...args);
};

async function runTest() {
    console.log('Starting Checkout Flow Test (Temporary Orders)...');

    // 1. Get a product for testing
    const product = await db.product.findFirst({
        where: { stock: { gt: 0 } }
    });

    if (!product) {
        console.log('No product with stock found. Creating a dummy product...');
        // Create dummy product if none exists
         await db.product.create({
            data: {
                id: 'TEST-PROD-001',
                name: 'Test Product',
                description: 'Test Description',
                longDescription: 'Long Test Description',
                price: 100,
                stock: 10,
                category: 'Test',
                imageUrls: [] as any,
                createdAt: new Date(),
            } as any
        });
    }

    const testProduct = await db.product.findFirst({ where: { name: 'Test Product' } }) || product!;

    console.log(`Using product: ${testProduct.name} (${testProduct.id})`);

    // 2. Mock Data
    const orderId = `TEST-${Date.now()}`;
    const customerData = {
        name: 'Test User',
        cpf: '123.456.789-00',
        phone: '(11) 99999-9999',
        address: 'Rua Teste',
        number: '123',
        neighborhood: 'Bairro Teste',
        city: 'Cidade Teste',
        state: 'TS',
        zip: '12345-678'
    };

    const orderData = {
        items: [{
            id: testProduct.id,
            name: testProduct.name,
            price: testProduct.price,
            quantity: 1,
            imageUrl: testProduct.imageUrl || ''
        }],
        total: testProduct.price,
        paymentMethod: 'Dinheiro',
        installments: 1,
        installmentValue: testProduct.price,
        createdByRole: 'customer'
    };

    // 3. Test Create Temporary Order
    console.log('Testing Create Temporary Order...');
    const createRes = await createTemporaryOrderAction({ orderData, customerData });
    
    if (!createRes.success || !createRes.id) {
        console.error('Failed to create temporary order:', createRes);
        return;
    }
    console.log('Temporary order created. ID:', createRes.id);

    // 4. Verify persistence
    const tempOrder = await db.temporaryOrder.findUnique({ where: { id: createRes.id } });
    if (!tempOrder) {
        console.error('Temporary order not found in DB!');
        return;
    }
    console.log('Temporary order verified in DB.');

    // 5. Test Cancel (to verify deletion)
    console.log('Testing Cancel Temporary Order...');
    const cancelRes = await cancelTemporaryOrderAction(createRes.id);
    if (!cancelRes.success) {
        console.error('Failed to cancel temporary order:', cancelRes);
        return;
    }
    
    const checkCancelled = await db.temporaryOrder.findUnique({ where: { id: createRes.id } });
    if (checkCancelled) {
        console.error('Temporary order still exists after cancel!');
        return;
    }
    console.log('Cancellation verified.');

    // 6. Test Confirm Flow
    console.log('Testing Confirm Flow...');
    // Re-create
    const createRes2 = await createTemporaryOrderAction({ orderData, customerData });
    const tempId2 = createRes2.id!;

    console.log('Confirming order...');
    
    // We expect this to potentially throw "Invariant: static generation store" because of revalidatePath
    // But the DB operation might succeed before that.
    try {
        const confirmRes = await confirmTemporaryOrderAction(tempId2);
        if (!confirmRes.success) {
             console.error('Failed to confirm order (logic error):', confirmRes);
             // Verify if it failed due to Next.js context
        } else {
             console.log('Order confirmed successfully.');
        }
    } catch (e: any) {
        console.log('Caught expected Next.js context error (revalidatePath). Checking DB...');
    }

    // 7. Verify Real Order
    // Since we don't know the exact ID generated by createOrderAction (it uses uuid or sequential),
    // we need to find it by customer/date or just check if temp order is gone.
    // Actually, createOrderAction returns the ID.
    // But if it threw error, we might not have it.
    // Let's check if Temporary Order is gone.
    
    const checkTemp2 = await db.temporaryOrder.findUnique({ where: { id: tempId2 } });
    if (!checkTemp2) {
        console.log('Temporary order was deleted, implying confirmation success (or partial success).');
        
        // Try to find the order for this customer created recently
        const recentOrder = await db.order.findFirst({
            where: {
                customer: {
                    path: '$.cpf',
                    equals: customerData.cpf
                }
            },
            orderBy: { createdAt: 'desc' }
        });
        
        if (recentOrder) {
             console.log('Real order found in DB:', recentOrder.id);
             // Cleanup
             await db.order.delete({ where: { id: recentOrder.id } });
        } else {
             console.log('Real order NOT found. Transaction might have rolled back.');
        }

    } else {
        console.error('Temporary order still exists after confirm! Confirmation failed.');
    }

    // Cleanup Customer
    await db.customer.deleteMany({ 
        where: { 
            cpf: customerData.cpf
        } 
    });

    console.log('Test Complete.');
    process.exit(0);
}

runTest().catch(e => {
    console.error(e);
    process.exit(1);
});
